version: 2
services:
  cups:
    image: canon-ufr-cups-airprint:latest
    build:
      # context: ./cups-avahi-airprint
      context: ./
    ports:
      - 631:631
    environment:
      CUPSADMIN: admin
      CUPSPASSWORD: heslo    
    volumes:
      - ./services:/services
      - ./config:/config

